# Generated by Django 2.2.12 on 2020-09-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_maps_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='label',
            field=models.CharField(default='My Location', max_length=25),
        ),
    ]
