# Generated by Django 2.2.12 on 2020-09-07 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0004_sharemaps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShareMaps',
            new_name='SharedMaps',
        ),
    ]
