# Generated by Django 2.2.12 on 2020-09-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20200907_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedmaps',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='maps',
            name='shared_with',
        ),
    ]
