# Generated by Django 2.2.12 on 2020-09-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedmaps', '0001_initial'),
        ('maps', '0007_auto_20200907_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='shared_with',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sharedmaps.SharedMaps'),
        ),
        migrations.DeleteModel(
            name='SharedMaps',
        ),
    ]
