# Generated by Django 2.2.12 on 2020-09-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedmaps', '0001_initial'),
        ('maps', '0009_auto_20200907_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='maps',
            name='shared_with',
            field=models.ManyToManyField(to='sharedmaps.SharedMaps'),
        ),
    ]
